

int autonNo=2;														//number of autonomour routines to pick from

//Commands for autonomous mode
#define DRIVE 1													//Drive command
#define SLOW 2													//Slow drive command
#define TURN 3
#define PAUSE 4													//Pause
#define SETGYRO 6												//Set the gyro
#define STACK 7
#define LIFTPOS 8
#define SWEEPPOS 9


#define BASEPOS 12
#define DRIVESTRAIGHT 13
#define STOPDRIVESTRAIGHT 14
#define CONENUMBER 15
#define PRELOAD 16

#define GOTBASE 17
#define NOBASE 18

#define SETCOMPASS 19
#define CONESIDE 20
#define RESETDRIVE 21

//CONDITIONAL PAUSES
#define BASEISDOWN -1
#define BASEISHALFDOWN -4
#define BASEISUP -2
#define DONESTACK -3
#define CONEUP -5

#define FORWARD 1
#define BACKWARD -1

#define BREAK 1
#define DRIFT 0

#define END 99													//Stop command list

//parameters
#define USER -4   											//Find angle in user code (override)
#define DISTANCE -5

#define LEFTWHITE -6
#define LEFTBLACK -7
#define RIGHTWHITE -8
#define RIGHTBLACK -9
#define EWHITE -10 //Either sensor reads black
#define EBLACK -11
#define BWHITE -12 //Both sensors read black
#define BBLACK -13


float auto0[]={0,END};						// Default starting table, do nothing

float spicyAuton[] = {
	0,
	//
	// FIX TURNS FOR THIS
	//
	BASEPOS,baseDownPos,
	NOBASE,													// SET TURN RATES
	PAUSE,0.5,											// PAUSE FOR DEPLOY
	LIFTPOS,2000,										// MOVE LIFT UP TO CALIBRATE
	SWEEPPOS,1,
	BASEPOS,baseUpPos,
	//BASEPOS,baseDownPos,						// MOVE BASE DOWN
	//PAUSE,BASEISHALFDOWN,5,					// PAUSE UNTIL BASE IS HALFWAY

	DRIVE,127,0,DISTANCE,0.5,1,
	PAUSE,0.25,
	DRIVE,-90,0,DISTANCE,0.5,1,
	SWEEPPOS,sweeperStackPos,									// MOVE SWEEPER TO MIDDLE
	//DRIVE,90,45,EWHITE,0.25,				// DRIVE TO BE SURE IN THE ZONE
	//DRIVE,-90,45,0.2,								// DRIVE BACK FROM THE WALL
	GOTBASE,												// TURN HARSHLY
	TURN,0,50,1,										// TURN TO FACE 45
	NOBASE,													// PRECISE TURN
	DRIVE,-60,50,0.02,							// MOVE AWAY FROM WALL
	NOBASE,													// PRECISE TURN
	TURN,0,50,1,										// TURN TO 45
	//LIFTPOS,1000,										// MOVE LIFT TO MIDDLE
	SWEEPPOS,sweeperStackPos,				// MOVE SWEEPER TO CENTRE SO IT DOESN'T CATCH
	RESETDRIVE,											// RESET DRIVE ENCODERS
	LIFTPOS,1000,
	DRIVE,-127,50,DISTANCE,2.2,3,		// DRIVE A DISTANCE ALONG DIAGNOL
	DRIVE,-127,50,0.25,							// DRIVE A LITTLE FURTHER TO HIT WALL
	PAUSE,0.25,											// BRIEF PAUSE

	// RESET GYRO

	DRIVE,90,0,0.2,									// DRIVE AWAY FROM WALL
	//DRIVE,0,90,0.5,									// TURN READY TO MOVE AWAY
	//DRIVE,-90,90,DISTANCE,0.2,0.5,	// MOVE AWAY FROM POLE
	NOBASE,													// PRECISE TURN
	TURN,0,5,1,										// TURN TO FACE 0
	DRIVE,-90,5,0.75,								// DRIVE INTO WALL

	PAUSE,0.5,											// SMALL PAUSE
	SETGYRO,0,											// RESET GYRO
	PAUSE,0.25,											// SMALL PAUSE
	DRIVE,90,0,DISTANCE,0.1,0.5,		// DRIVE AWAY FROM WALL

	// TURN READY FOR NEXT BASE


	GOTBASE,												// TURN HARSHLY
	TURN,0,270,1,									// TURN TO FACE NEXT BASE
	LIFTPOS,2000,
	NOBASE,													// NORMAL TURN
	TURN,0,270,1,										// FINISH TURN
	TURN,0,270,1,										// FINISH TURN
	//	TURN,0,270,1,										// FINISH TURN

	// PREPARE FOR BASE

	BASEPOS,baseDownPos,						// MOVE BASE LIFT DOWN
	PAUSE,BASEISHALFDOWN,5,					// WAIT TILL ITS READY
	PAUSE,1.5,												// PAUSE TO LET IT FINISH

	// DRIVE TO GET BASE

	// PAUSE,20,												// LET SMART MOTORS REST

	DRIVESTRAIGHT,									// DON'T LET SMART MOTORS 'HELP'
	DRIVE,60,270,0.1,								// DON'T JERK
	DRIVE,127,270,EWHITE,2,					// DRIVE TO FIRST WHITE LINE
	DRIVE,127,270,0.1,
	DRIVE,127,270,EWHITE,2,					// DRIVE TO SECOND WHITE LINE
	DRIVE,127,270,0.5,							// DRIVE A LITTLE FURTHER
	STOPDRIVESTRAIGHT,							// LET SMART MOTORS 'HELP'

	// PICK UP BASE

	BASEPOS,baseUpPos,							// PICKUP BASE
	PAUSE,BASEISUP,4,								// WAIT UNTIL BASE IS IN
	BASEPOS,-1,											// STOP MOVING BASE LIFT
	PAUSE,0.5,											// EXTRA PAUSE SO IT DOESN'T FALL OUT
	GOTBASE,												// CHANGE TURN VALUES TO BASE

	CONESIDE,RIGHT,									// STACKING FROM THE RIGHT SIDE
	PRELOAD,												// DO THE PRELOAD
	PAUSE,DONESTACK,5,
	// DRIVE BACK TO 5PT ZONE

	DRIVE,-127,270,BBLACK,2,				// DRIVE OFF OF TILE
	DRIVE,-127,270,EWHITE,2,				// DRIVE TO FIRST WHITE LINE
	DRIVE,-127,270,0.2,							// DRIVE A LITTLE FURTHER
	DRIVE,-127,270,EWHITE,2,				// DRIVE TO SECOND WHITE LINE
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,-127,270,
	DISTANCE,0.25,0.5,							// DRIVE BACKWARDS A LITTLE FURTHER
	LIFTPOS,1000,										// MOVE LIFT READY FOR BASE TIP
	SWEEPPOS,10,										// MOVE SWEEPER REAFY FOR BASE TIP
	// GET READY TO PLACE BASE

	// DRIVE READY TO PLACE

	GOTBASE,
	TURN,0,45,0.5,									// TURN PERP. TO ZONE
	TURN,0,45,0.5,									// FINISH TURN
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,90,45,DISTANCE,0.1,0.5,	// DRIVE ALONG ZONE

	// PREPARE TO PLACE

	GOTBASE,
	LIFTPOS,-1,											// STOP MOVING LIFT
	TURN,0,135,0.5,								// TURN TO FACE ZONE
	DRIVE,-60,135,0.2,
	GOTBASE,
	TURN,0,125,1,								// TURN TO FACE ZONE

	DRIVE,60,135,DISTANCE,0.15,0.3, //DRIVE TO EDGE OF ZONE

	// PLACE BASE

	BASEPOS,baseDownPos,						// PUT DOWN SECOND BASE
	PAUSE,BASEISDOWN,6,							// WAIT UNTIL BASE IS DOWN																	// BASE No. 2 IS DONE
	PAUSE,0.5,											// PAUSE A LITTLE LONGER

	// DRIVE BACK FROM ZONE

	NOBASE,													// SET TURN VALUES
	SWEEPPOS,10,										// BRING SWEEPER TO ONE SIDE READY FOR BASE TIP
	DRIVE,60,135,0.2,								// DRIVE AT ZONE TO DROP BASE
	DRIVE,-127,135,DISTANCE,0.35,1,	// DRIVE BACKWARDS AWAY FROM ZONE
	BASEPOS,baseUpPos,							// BRING BASE LIFT UP
	DRIVE,90,135,0.025,							// BREAK TO STOP

	// KNOCK OVER BASE

	LIFTPOS,1000,										// BRING LIFT TO BASE TIP POSITION
	NOBASE,
	TURN,0,155,1,
	TURN,0,155,0.5,
	DRIVE,-90,155,DISTANCE,0.75,1.5,		// DRIVE TO BASE
	LIFTPOS,liftTopPos,							// MOVE LIFT UP
	PAUSE,1,												// WAIT TILL LIFT IS READY
	GOTBASE,												// TURN HARD
	TURN,0,135,0.5,								// TURN TO AIM FOR 5 Pt. ZONE LINE
	DRIVE,70,135,EWHITE,1,					// DRIVE TO WHITE LINE AND KNOCK OVER BASE
	DRIVE,-90,135,0.05,							// BACK PULSE TO STOP ON LINE
	NOBASE,
	LIFTPOS,-1,											// TURN LIFT OFF
	SWEEPPOS,-1,
	END,
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

float regAuton[] = {							// SHOULD GET TWO BASES IN THE 10 PT. ZONE, WITH ONE CONE, AND KNOCK OVER TWO ENEMY BASES
	0,															// START AT 0 DEGREES

	/*DRIVESTRAIGHT,
	RESETDRIVE,
	DRIVE,60,0,DISTANCE,2,2,
	STOPDRIVESTRAIGHT,
	NOBASE,
	TURN,0,90,2,
	DRIVE,60,90,0.5,
	DRIVE,-60,90,0.1,
	PAUSE,0.5,
	DRIVE,127,90,DISTANCE,1,1,
	END,*/

	/*NOBASE,
	TURN,0,90,2,
	TURN,0,270,2,
	TURN,0,180,2,
	DRIVE,0,0,2,
	PAUSE,15,
	GOTBASE,
	TURN,0,90,2,
	TURN,0,270,2,
	TURN,0,180,2,
	DRIVE,0,0,2,
	END,*/

	// PREPARE TO DRIVE TO BASE
	DRIVESTRAIGHT,
	BASEPOS,baseDownPos,
	NOBASE,													// SET TURN RATES
	PAUSE,0.5,											// PAUSE FOR DEPLOY
	LIFTPOS,2000,										// MOVE LIFT UP TO CALIBRATE
	//BASEPOS,baseDownPos,						// MOVE BASE DOWN
	PAUSE,BASEISHALFDOWN,5,					// PAUSE UNTIL BASE IS HALFWAY
	SWEEPPOS,1,										// MOVE SWEEPER TO EDGE

	// DRIVE TO BASE

	DRIVE,60,0,0.1,									// DON'T JERK
	DRIVE,127,0,LEFTWHITE,2,				// DRIVE TO DIAGNOL WHITE LINE
	DRIVE,127,0,RIGHTWHITE,2,				// DRIVE TO NEXT PART OF IT
	SWEEPPOS,sweeperStackPos,				// MOVE SWEEPER TO MIDDLE
	DRIVE,127,0,0.125,							// MAKE SURE OFF LINE
	DRIVE,127,0,EWHITE,2,						// DRIVE TO PERPENDICULAR LINE

	// PICKUP BASE

	LIFTPOS,-1,											// STOP MOVING LIFT
	BASEPOS,baseUpPos,							// PICKUP BASE
	PAUSE,BASEISUP,4,								// WAIT UNTIL BASE IS IN
	BASEPOS,-1,											// STOP MOVING BASE LIFT
	PAUSE,0.5,											// EXTRA PAUSE SO IT DOESN'T FALL OUT
	GOTBASE,												// CHANGE TURN VALUES TO BASE
	STOPDRIVESTRAIGHT,

	// STACK PRELOAD

	CONESIDE,RIGHT,									// STACKING FROM THE RIGHT SIDE
	PRELOAD,												// DO THE PRELOAD
	PAUSE,DONESTACK,2,							// WAIT UNTIL IT IS DONE
	//LIFTPOS,1000,										// MOVE LIFT READY FOR RELEASE AND BASE TIP

	// DRIVE TO 5PT ZONE

	DRIVESTRAIGHT,
	DRIVE,-127,0,BBLACK,2,					// DRIVE OFF THE BLUE TILE
	DRIVE,-127,0,EWHITE,2,					// DRIVE TO FIRST WHITE LINE
	DRIVE,-127,0,0.2,								// DRIVE PAST IT
	DRIVE,-127,0,EWHITE,2,					// DRIVE TO DIAGNOL LINE
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,-127,0,DISTANCE,0.25,1,		// DRIVE A LITTLE FURTHER
	DRIVE,90,0,0.05,								// BREAK
	STOPDRIVESTRAIGHT,
	GOTBASE,
	//
	PAUSE,DONESTACK,8,							// WAIT UNTIL IT IS DONE
	LIFTPOS,1000,										// MOVE LIFT READY FOR RELEASE AND BASE TIP
	//

	// DRIVE READY TO PLACE
	GOTBASE,
	TURN,0,225,0.5,								// TURN PERP. TO ZONE
	TURN,0,225,0.5,								// FINISH TURN
	RESETDRIVE,											// RESET DRIVE ENCODERS
	NOBASE,
	DRIVE,90,225,DISTANCE,0.1,0.5,	// DRIVE ALONG ZONE
	//DRIVE,-90,225,DISTANCE,0.1,0.5,	// DRIVE ALONG ZONE

	// PREPARE TO PLACE


	LIFTPOS,-1,											// STOP MOVING LIFT
	GOTBASE,
	TURN,0,135,0.5,								// TURN TO FACE ZONE
	DRIVE,-60,135,0.1,							// LITTLE JERK TO HELP TURN
	GOTBASE,
	TURN,0,135,1,									// TURN TO FACE ZONE
	TURN,0,145,1,									// FINISH TURN
	//TURN,0,135,1,									// FINISH TURN MORE

	// PLACE

	RESETDRIVE,
	NOBASE,
	DRIVE,60,135,DISTANCE,0.15,0.3,	//DRIVE TO EDGE OF ZONE
	STOPDRIVESTRAIGHT,
	BASEPOS,baseDownPos,						// PUT DOWN FIRST BASE
	PAUSE,BASEISDOWN,6,							// WAIT UNTIL BASE IS DOWN																	// BASE No. 1
	PAUSE,0.5,											// PAUSE A LITTLE LONGER

	// DRIVE BACK FROM ZONE

	NOBASE,													// SET TURN VALUES
	SWEEPPOS,10,										// BRING SWEEPER TO ONE SIDE READY FOR BASE TIP
	DRIVE,60,135,0.3,								// DRIVE AT ZONE TO DROP BASE
	RESETDRIVE,
	DRIVE,-127,135,DISTANCE,0.55,1,	// DRIVE BACKWARDS AWAY FROM ZONE
	BASEPOS,baseUpPos,							// BRING BASE LIFT UP
	DRIVE,90,135,0.025,							// BREAK TO STOP

	// KNOCK OVER BASE

	LIFTPOS,1000,										// BRING LIFT TO BASE TIP POSITION
	NOBASE,
	TURN,0,125,1,
	TURN,0,125,0.5,
	RESETDRIVE,
	DRIVE,-127,125,DISTANCE,0.55,1.5,		// DRIVE TO BASE
	LIFTPOS,liftTopPos,							// MOVE LIFT UP
	PAUSE,1.5,												// WAIT TILL LIFT IS READY
	GOTBASE,												// TURN HARD
	TURN,0,90,0.2,
	TURN,0,180,0.2,									// SHIMMY TO GET LOCKED IN
	TURN,0,140,0.2,
	//DRIVESTRAIGHT,									// IGNORE S.M.
	NOBASE,
	DRIVE,70,150,EWHITE,2,					// DRIVE TO WHITE LINE AND KNOCK OVER BASE
	DRIVE,-90,150,0.2,							// BACK PULSE TO STOP ON LINE
	STOPDRIVESTRAIGHT,							// USE SMART MOTORS
	NOBASE,													// TURN NORMAL
	// NAVIGATE TO OTHER SIDE OF 5 PT ZONE		// 50 angles were 45

	PAUSE,0.5,											// TAKE A BREATHER
	//DRIVE,90,45,EWHITE,0.25,				// DRIVE TO BE SURE IN THE ZONE
	//DRIVE,-90,45,0.2,								// DRIVE BACK FROM THE WALL
	GOTBASE,												// TURN HARSHLY
	TURN,0,50,1,										// TURN TO FACE 45
	NOBASE,													// PRECISE TURN
	DRIVE,-60,50,0.02,							// MOVE AWAY FROM WALL
	NOBASE,
	TURN,0,50,1,										// TURN TO 45
	LIFTPOS,1000,										// MOVE LIFT TO MIDDLE
	SWEEPPOS,sweeperStackPos,				// MOVE SWEEPER TO CENTRE SO IT DOESN'T CATCH
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,-127,50,DISTANCE,2.2,3,		// DRIVE A DISTANCE ALONG DIAGNOL
	DRIVE,-127,50,0.25,							// DRIVE A LITTLE FURTHER TO HIT WALL
	PAUSE,0.25,											// BRIEF PAUSE

	// RESET GYRO

	DRIVE,90,0,0.2,									// DRIVE AWAY FROM WALL
	//DRIVE,0,90,0.5,									// TURN READY TO MOVE AWAY
	//DRIVE,-90,90,DISTANCE,0.2,0.5,	// MOVE AWAY FROM POLE
	NOBASE,
	TURN,0,5,1,										// TURN TO FACE 0
	DRIVE,-90,5,0.75,								// DRIVE INTO WALL

	PAUSE,0.5,											// SMALL PAUSE
	SETGYRO,0,											// RESET GYRO
	PAUSE,0.25,											// SMALL PAUSE
	RESETDRIVE,
	DRIVE,90,0,DISTANCE,0.1,0.5,		// DRIVE AWAY FROM WALL

	// TURN READY FOR NEXT BASE

	GOTBASE,												// TURN HARSHLY
	TURN,0,270,1,									// TURN TO FACE NEXT BASE
	NOBASE,													// NORMAL TURN
	TURN,0,270,1,										// FINISH TURN
	TURN,0,270,1,										// FINISH TURN
	//	TURN,0,270,1,										// FINISH TURN

	// PREPARE FOR BASE

	BASEPOS,baseDownPos,						// MOVE BASE LIFT DOWN
	PAUSE,BASEISHALFDOWN,5,					// WAIT TILL ITS READY
	PAUSE,1.5,												// PAUSE TO LET IT FINISH

	// DRIVE TO GET BASE

	// PAUSE,20,												// LET SMART MOTORS REST

	DRIVESTRAIGHT,									// DON'T LET SMART MOTORS 'HELP'
	DRIVE,60,270,0.1,								// DON'T JERK
	DRIVE,127,270,EWHITE,2,					// DRIVE TO FIRST WHITE LINE
	DRIVE,127,270,0.1,
	DRIVE,127,270,EWHITE,2,					// DRIVE TO SECOND WHITE LINE
	DRIVE,127,270,0.5,							// DRIVE A LITTLE FURTHER
	STOPDRIVESTRAIGHT,							// LET SMART MOTORS 'HELP'

	// PICK UP BASE

	BASEPOS,baseUpPos,							// PICKUP BASE
	PAUSE,BASEISUP,4,								// WAIT UNTIL BASE IS IN
	BASEPOS,-1,											// STOP MOVING BASE LIFT
	PAUSE,0.5,											// EXTRA PAUSE SO IT DOESN'T FALL OUT
	GOTBASE,												// CHANGE TURN VALUES TO BASE
	LIFTPOS,1000,										// MOVE LIFT READY FOR BASE TIP
	SWEEPPOS,10,										// MOVE SWEEPER REAFY FOR BASE TIP

	// DRIVE BACK TO 5PT ZONE

	DRIVE,-127,270,BBLACK,2,				// DRIVE OFF OF TILE
	DRIVE,-127,270,EWHITE,2,				// DRIVE TO FIRST WHITE LINE
	DRIVE,-127,270,0.2,							// DRIVE A LITTLE FURTHER
	DRIVE,-127,270,EWHITE,2,				// DRIVE TO SECOND WHITE LINE
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,-127,270,
	DISTANCE,0.25,0.5,							// DRIVE BACKWARDS A LITTLE FURTHER

	// GET READY TO PLACE BASE

	// DRIVE READY TO PLACE

	NOBASE,
	TURN,0,45,0.5,									// TURN PERP. TO ZONE
	TURN,0,45,0.5,									// FINISH TURN
	RESETDRIVE,											// RESET DRIVE ENCODERS
	DRIVE,90,45,DISTANCE,0.1,0.5,	// DRIVE ALONG ZONE

	// PREPARE TO PLACE

	LIFTPOS,-1,											// STOP MOVING LIFT
	NOBASE,
	TURN,0,135,0.5,								// TURN TO FACE ZONE
	DRIVE,-60,135,0.2,
	NOBASE,
	TURN,0,125,1,								// TURN TO FACE ZONE
	RESETDRIVE,
	DRIVE,60,135,DISTANCE,0.15,0.3, //DRIVE TO EDGE OF ZONE

	// PLACE BASE

	BASEPOS,baseDownPos,						// PUT DOWN SECOND BASE
	PAUSE,BASEISDOWN,6,							// WAIT UNTIL BASE IS DOWN																	// BASE No. 2 IS DONE
	PAUSE,0.5,											// PAUSE A LITTLE LONGER

	// DRIVE BACK FROM ZONE

	NOBASE,													// SET TURN VALUES
	SWEEPPOS,10,										// BRING SWEEPER TO ONE SIDE READY FOR BASE TIP
	DRIVE,60,135,0.2,								// DRIVE AT ZONE TO DROP BASE
	RESETDRIVE,
	DRIVE,-127,135,DISTANCE,0.35,1,	// DRIVE BACKWARDS AWAY FROM ZONE
	BASEPOS,baseUpPos,							// BRING BASE LIFT UP
	DRIVE,90,135,0.025,							// BREAK TO STOP

	// KNOCK OVER BASE

	LIFTPOS,1000,										// BRING LIFT TO BASE TIP POSITION
	NOBASE,
	TURN,0,155,1,
	TURN,0,155,0.5,
	RESETDRIVE,
	DRIVE,-90,155,DISTANCE,0.75,1.5,		// DRIVE TO BASE
	LIFTPOS,liftTopPos,							// MOVE LIFT UP
	PAUSE,1,												// WAIT TILL LIFT IS READY
	GOTBASE,												// TURN HARD
	TURN,0,135,0.5,								// TURN TO AIM FOR 5 Pt. ZONE LINE
	DRIVE,70,135,EWHITE,1,					// DRIVE TO WHITE LINE AND KNOCK OVER BASE
	DRIVE,-90,135,0.05,							// BACK PULSE TO STOP ON LINE
	NOBASE,
	LIFTPOS,-1,											// TURN LIFT OFF
	SWEEPPOS,-1,

	END,														// END OF ROUTINE
};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
